// Categories the user can choose from

const categories = {
    Maths: [
        "Basic Maths",
        "Algebra",
        "Geometry",
        "Trigonometry",
        "Calculus",
        "Statistics",
        "Linear Algebra",
        "Differential Equations",
        "Number Theory",
        "Discrete Mathematics",
        "Mathematical Logic",
        "Real Analysis",
        "Complex Analysis",
        "Probability Theory",
        "Numerical Methods",
        "Mathematical Modeling",
        "Game Theory",
        "Topological Spaces",
        "Abstract Algebra",
        "Mathematics for Economics",
    ],
    Physics: [
        "Mechanics",
        "Electromagnetism",
        "Thermodynamics",
        "Quantum Physics",
        "Optics",
        "Nuclear Physics",
        "Astrophysics",
        "Condensed Matter Physics",
        "Classical Mechanics",
        "Fluid Dynamics",
        "Relativity",
        "Particle Physics",
        "Biophysics",
        "Geophysics",
        "Acoustics",
        "Plasma Physics",
        "Statistical Mechanics",
        "Optical Engineering",
        "Materials Physics",
        "Computational Physics",
    ],
    Chemistry: [
        "Organic Chemistry",
        "Inorganic Chemistry",
        "Physical Chemistry",
        "Analytical Chemistry",
        "Biochemistry",
        "Materials Science",
        "Environmental Chemistry",
        "Chemical Engineering",
        "Theoretical Chemistry",
        "Nanotechnology",
        "Pharmaceutical Chemistry",
        "Forensic Chemistry",
        "Chemical Biology",
        "Electrochemistry",
        "Green Chemistry",
        "Computational Chemistry",
        "Surface Chemistry",
        "Solid State Chemistry",
        "Industrial Chemistry",
        "Radiochemistry",
    ],
    Biology: [
        "Cell Biology",
        "Genetics",
        "Ecology",
        "Human Biology",
        "Microbiology",
        "Botany",
        "Zoology",
        "Evolution",
        "Physiology",
        "Molecular Biology",
        "Neurobiology",
        "Developmental Biology",
        "Immunology",
        "Biotechnology",
        "Marine Biology",
        "Environmental Biology",
        "Ecophysiology",
        "Population Biology",
        "Plant Biology",
        "Conservation Biology",
    ],
    "Computer Science": [
        "Programming",
        "Data Structures",
        "Algorithms",
        "Artificial Intelligence",
        "Web Development",
        "Mobile Development",
        "Databases",
        "Cybersecurity",
        "Software Engineering",
        "Game Development",
        "Machine Learning",
        "Data Science",
        "Computer Graphics",
        "Cloud Computing",
        "DevOps",
        "Networking",
        "Human-Computer Interaction",
        "Information Security",
        "Distributed Systems",
        "Blockchain Technology",
    ],
    Languages: [
        "English",
        "Spanish",
        "French",
        "German",
        "Mandarin",
        "Japanese",
        "Italian",
        "Russian",
        "Portuguese",
        "Arabic",
        "Korean",
        "Dutch",
        "Swedish",
        "Hindi",
        "Turkish",
        "Thai",
        "Hebrew",
        "Greek",
        "Indonesian",
        "Vietnamese",
    ],
    Music: [
        "Piano",
        "Guitar",
        "Violin",
        "Music Theory",
        "Singing",
        "Drums",
        "Composition",
        "Music Production",
        "Songwriting",
        "Music History",
        "Jazz",
        "Classical Music",
        "Pop Music",
        "Rock Music",
        "Electronic Music",
        "Music Technology",
        "World Music",
        "Music Therapy",
        "Film Scoring",
        "Arranging",
    ],
    "Art & Design": [
        "Drawing",
        "Painting",
        "Graphic Design",
        "Photography",
        "Illustration",
        "Fashion Design",
        "3D Modeling",
        "Animation",
        "Interior Design",
        "Art History",
        "Sculpture",
        "Ceramics",
        "Digital Art",
        "Printmaking",
        "Textile Design",
        "Landscape Design",
        "Product Design",
        "User Experience (UX) Design",
        "Video Editing",
        "Creative Writing",
    ],
    Business: [
        "Entrepreneurship",
        "Marketing",
        "Finance",
        "Project Management",
        "Business Strategy",
        "Human Resources",
        "Accounting",
        "Economics",
        "Operations Management",
        "Business Ethics",
        "International Business",
        "E-Commerce",
        "Supply Chain Management",
        "Business Analytics",
        "Real Estate",
        "Investment Banking",
        "Public Relations",
        "Nonprofit Management",
        "Corporate Finance",
        "Franchise Management",
    ],
    Sports: [
        "Yoga",
        "Fitness Training",
        "Swimming",
        "Tennis",
        "Football",
        "Basketball",
        "Martial Arts",
        "Dance",
        "Running",
        "Nutrition for Athletes",
        "Cycling",
        "Baseball",
        "Soccer",
        "Athletics",
        "CrossFit",
        "Pilates",
        "Rock Climbing",
        "Gymnastics",
        "Rugby",
        "Sports Psychology",
    ],
    History: [
        "Ancient History",
        "Modern History",
        "World History",
        "Cultural History",
        "Political History",
        "Military History",
        "Social History",
        "Economic History",
        "History of Science",
        "History of Technology",
        "History of Art",
        "History of Music",
        "Colonial History",
        "Post-Colonial Studies",
        "Women's History",
        "Environmental History",
        "History of Education",
        "Maritime History",
        "Labor History",
        "History of Religion",
    ],
    "Social Sciences": [
        "Psychology",
        "Sociology",
        "Anthropology",
        "Political Science",
        "Economics",
        "International Relations",
        "Human Geography",
        "Cultural Studies",
        "Criminology",
        "Social Work",
        "Demography",
        "Development Studies",
        "Media Studies",
        "Gender Studies",
        "Urban Studies",
        "Rural Studies",
        "Ethnic Studies",
        "Psychological Anthropology",
        "Behavioral Economics",
        "Social Justice",
    ],
    Literature: [
        "English Literature",
        "World Literature",
        "Poetry",
        "Creative Writing",
        "Comparative Literature",
        "Literary Theory",
        "Drama",
        "Children's Literature",
        "Science Fiction",
        "Literature and Gender",
        "Mystery Literature",
        "Historical Fiction",
        "Non-Fiction",
        "Literature of the Americas",
        "Classic Literature",
        "Postcolonial Literature",
        "Contemporary Fiction",
        "Young Adult Literature",
        "Graphic Novels",
        "Fantasy Literature",
    ],
    "Test Prep": [
        "SAT",
        "ACT",
        "GRE",
        "GMAT",
        "LSAT",
        "IELTS",
        "TOEFL",
        "AP Exams",
        "MCAT",
        "Subject Tests",
        "PSAT",
        "SAT II",
        "ACCUPLACER",
        "ASVAB",
        "Bar Exam",
        "NCLEX",
        "CFA",
        "PRAXIS",
        "DAT",
        "OAT",
    ],
    Engineering: [
        "Mechanical Engineering",
        "Electrical Engineering",
        "Civil Engineering",
        "Chemical Engineering",
        "Software Engineering",
        "Aerospace Engineering",
        "Biomedical Engineering",
        "Environmental Engineering",
        "Industrial Engineering",
        "Systems Engineering",
        "Structural Engineering",
        "Geotechnical Engineering",
        "Petroleum Engineering",
        "Transportation Engineering",
        "Robotics Engineering",
        "Control Systems Engineering",
        "Nuclear Engineering",
        "Materials Engineering",
        "Construction Engineering",
        "Agricultural Engineering",
    ],
    "Health & Wellness": [
        "Nutrition",
        "Mental Health",
        "First Aid",
        "Meditation",
        "Personal Development",
        "Yoga",
        "Fitness Coaching",
        "Stress Management",
        "Wellness Coaching",
        "Healthy Cooking",
        "Sleep Science",
        "Physical Therapy",
        "Alternative Medicine",
        "Nutrition for Athletes",
        "Mindfulness",
        "Public Health",
        "Chronic Illness Management",
        "Weight Loss Coaching",
        "Addiction Recovery",
        "Holistic Health",
    ],
    Philosophy: [
        "Ethics",
        "Logic",
        "Metaphysics",
        "Epistemology",
        "Political Philosophy",
        "Philosophy of Mind",
        "Philosophy of Science",
        "Aesthetics",
        "History of Philosophy",
        "Eastern Philosophy",
        "Western Philosophy",
        "Existentialism",
        "Phenomenology",
        "Philosophy of Language",
        "Philosophy of Religion",
        "Pragmatism",
        "Stoicism",
        "Utilitarianism",
        "Moral Philosophy",
        "Social Philosophy",
    ],
    "Environmental Science": [
        "Ecology",
        "Conservation Biology",
        "Environmental Policy",
        "Climate Change",
        "Sustainable Development",
        "Renewable Energy",
        "Soil Science",
        "Water Resources",
        "Wildlife Management",
        "Environmental Chemistry",
        "Marine Conservation",
        "Biodiversity",
        "Environmental Impact Assessment",
        "Ecosystem Services",
        "Waste Management",
        "Environmental Law",
        "Urban Ecology",
        "Sustainable Agriculture",
        "Climate Policy",
        "Environmental Justice",
    ],
    Theology: [
        "Comparative Religion",
        "Biblical Studies",
        "Philosophy of Religion",
        "Ethics in Religion",
        "World Religions",
        "Religious History",
        "Theology and Society",
        "Mysticism",
        "Religious Texts",
        "Interfaith Dialogue",
        "Theology of the Body",
        "Sacred Music",
        "History of Christianity",
        "History of Islam",
        "Religious Rituals",
        "Social Justice in Religion",
        "Environmental Theology",
        "Women in Religion",
        "Theology and Science",
        "Religious Fundamentalism",
    ],
    "Culinary Arts": [
        "Baking",
        "Cooking Techniques",
        "Nutrition",
        "International Cuisine",
        "Food Presentation",
        "Culinary Management",
        "Food Safety",
        "Wine Pairing",
        "Meal Planning",
        "Pastry Arts",
        "Gastronomy",
        "Vegetarian Cooking",
        "Vegan Cooking",
        "Barbecue Techniques",
        "Culinary History",
        "Global Street Food",
        "Fermentation Techniques",
        "Chocolate Making",
        "Healthy Meal Prep",
        "Food Photography",
    ],
    "Graphic Design": [
        "Logo Design",
        "Branding",
        "Print Design",
        "Web Design",
        "UI/UX Design",
        "Motion Graphics",
        "Typography",
        "Color Theory",
        "Illustration",
        "Packaging Design",
        "Infographics",
        "Advertising Design",
        "Signage Design",
        "Environmental Graphics",
        "Marketing Materials",
        "Editorial Design",
        "Photo Manipulation",
        "3D Design",
        "Character Design",
        "Design for Social Media",
    ],
    Fashion: [
        "Fashion Design",
        "Fashion Illustration",
        "Textile Design",
        "Fashion History",
        "Sustainable Fashion",
        "Fashion Marketing",
        "Costume Design",
        "Fashion Merchandising",
        "Pattern Making",
        "Fashion Photography",
        "Fashion Branding",
        "Retail Management",
        "Fashion Styling",
        "Runway Production",
        "Fashion Technology",
        "Footwear Design",
        "Accessories Design",
        "Fashion Business",
        "Fashion Show Production",
        "Fashion Journalism",
    ],
    "Digital Marketing": [
        "SEO",
        "Content Marketing",
        "Social Media Marketing",
        "Email Marketing",
        "PPC Advertising",
        "Affiliate Marketing",
        "Influencer Marketing",
        "Brand Strategy",
        "Market Research",
        "Analytics",
        "Conversion Rate Optimization",
        "Digital Strategy",
        "Web Analytics",
        "Mobile Marketing",
        "Video Marketing",
        "E-commerce Marketing",
        "Online Reputation Management",
        "Lead Generation",
        "Community Management",
        "Digital Advertising",
    ],
    "Real Estate": [
        "Real Estate Investment",
        "Property Management",
        "Commercial Real Estate",
        "Residential Real Estate",
        "Real Estate Development",
        "Real Estate Appraisal",
        "Real Estate Marketing",
        "Real Estate Law",
        "Negotiation Skills",
        "Real Estate Finance",
        "Real Estate Economics",
        "Real Estate Brokerage",
        "Urban Development",
        "Real Estate Photography",
        "Land Use Planning",
        "Commercial Leasing",
        "Real Estate Taxation",
        "Real Estate Technology",
        "Short-Term Rentals",
        "Real Estate Trends",
    ],
    "Interior Design": [
        "Residential Design",
        "Commercial Design",
        "Sustainable Design",
        "Color Theory",
        "Space Planning",
        "Furniture Design",
        "Lighting Design",
        "Kitchen and Bath Design",
        "Interior Architecture",
        "Design Psychology",
        "Textile and Material Selection",
        "Visual Merchandising",
        "Historic Preservation",
        "Universal Design",
        "Landscape Design",
        "Commercial Spaces",
        "Lighting Design",
        "Workplace Design",
        "Retail Design",
        "Event Design",
    ],
    "Public Speaking": [
        "Speech Writing",
        "Presentation Skills",
        "Storytelling Techniques",
        "Body Language",
        "Voice Modulation",
        "Audience Engagement",
        "Overcoming Fear",
        "Persuasive Speaking",
        "Effective Communication",
        "Debate Techniques",
        "Business Presentations",
        "Impromptu Speaking",
        "Speech Delivery",
        "Non-Verbal Communication",
        "Networking Skills",
        "Virtual Presentations",
        "Crisis Communication",
        "Keynote Speaking",
        "Communication Styles",
        "Cross-Cultural Communication",
    ],
    Parenting: [
        "Child Development",
        "Positive Discipline",
        "Education Strategies",
        "Nutrition for Kids",
        "Special Needs Parenting",
        "Parent-Child Communication",
        "Behavior Management",
        "Work-Life Balance",
        "Parenting Styles",
        "Emotional Intelligence for Kids",
        "Teen Parenting",
        "Early Childhood Education",
        "Positive Parenting",
        "Single Parenting",
        "Crisis Management",
        "Parenting and Mental Health",
        "Co-parenting",
        "Adoptive Parenting",
        "Cultural Influences on Parenting",
        "Parenting in the Digital Age",
    ],
};

export default categories;
